main: edu.unca.ajrobine.FirstPlugIn.FirstPlugIn
name: FirstPlugIn
version: ${project.version}
author: AndrewRobinette
description: ${project.description}
commands:
  FirstPlugIn:
    description: the 'root' or 'base of my first plugin.
    usage: /<FirstPlugIn> command 
    permission: FirstPlugIn.*
permissions:
  FirstPlugIn.*:
    description: permissions for the commands in this plugin.
    default: true
    children:
      FirstPlugIn.message:
        description: allows the user to set a sample message
      FirstPlugIn.cake:
        description: give the player some cake
      FirstPlugIn.kick:
        description: kicks a player out of the game
      FirstPlugIn.extrahealth:
        description: gives a player extra health when they ask for it
      FirstPlugIn.superspeed:
        description: allows players to move much faster than normal
      FirstPlugIn.freeexperience:
        description: allows players to gain 100 points of experience
      FirstPlugIn.maxlevel:
        description: punishes players who think that they will cheat their way to victory by bumping them down to level 1 instead of max level as advertised
      FirstPlugIn.creatingtrees:
        description: allows players to create pine trees
      FirstPlugIn.notcreatingtrees:
        description: turns off the ability for creating trees       